### ISSUE TITLE
Make the repository a template

### ISSUE THREAD

**Issue by psy667** [anandundavia/express-api-structure#2]

**Comment by anandundavia** [comment]
Can you elaborate !?

**Comment by psy667** [comment]
Yes.
You can make the repository a template, so users can generate new repositories with the same directory structure and files.

https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository

Thanks

**Comment by anandundavia** [comment]
Oh Okay, I did not know that. 
Thanks.

This repository is now a template 💯 
Closing the issue :D
